myvideo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repository.urls', namespace='repository')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

repository/urls.py
from django.urls import path
from .import views

app_name = 'repository'
urlpatterns = [
    path('login/', views.userLogin, name='userLogin'),
    path('registration/', views.registration, name='registration'),
    path('home/', views.home, name='home'),
    path('create/playlist', views.createPlaylist, name='createPlaylist'),
    path('playlist/video/<str:id>', views.ViewVideoPlaylist, name='ViewVideoPlaylist'),
    path('create/video/<str:id>', views.CreateVideoPlaylist, name='CreateVideoPlaylist'),
    #path('teacher/registration', views.teacherRegistration, name='teacherRegistration'),
]

repository/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Teacher(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	avatar= models.ImageField(blank=True)
	about = models.CharField(max_length=200, blank=True, null=True)
	qualification = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.user.username


class Playlist(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='playlist/images' , null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.creator.username

	def get_absolute_url(self):
		return reverse('repository:ViewVideoPlaylist', args=[self.id,])


class Video(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
	file = models.FileField(upload_to='videos/')
	description = models.CharField(max_length=200, blank=True)
	likes = models.ManyToManyField(User, related_name='likes', blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.creator.username


class Student(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	avatar = models.ImageField(blank=True)
	follow = models.ManyToManyField(Teacher, related_name='following', blank=True) 

	def __str__(self):
		return self.user.username


'''class Avatar(models.Model):
	avatar_user = models.ForeignKey(User, on_delete = models.CASCADE)
	file = models.ImageField(upload_to='profile_pics', null=True, blank=True)

	class Meta:
		verbose_name = 'avatarPhoto'
		verbose_name_plural = 'avatarPhotos'

	def __str__(self):
		return self.avatar_user.username'''


class Comment(models.Model):
	video = models.ForeignKey(Video, on_delete = models.CASCADE )
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='replies')
	content = models.TextField(max_length=200)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.content[:20], str(self.user.username))

repository/forms.py
from django import forms
from .models import Teacher, Playlist, Video, Student, Comment
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
	username= forms.CharField(label="Username",max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(UserCreationForm):
	first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control', 'placeholder':'Fist Name'}))
	last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Last Name'}))
	username = forms.CharField(label="Username",max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'}))
	password1 = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))
	password2 = forms.CharField(label="Confirm Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Confirm Password'}))

	def clean_username(self):
		username = self.cleaned_data['username']
		qs = User.objects.filter(username=username)
		if qs.exists():
			raise ValidationError('Username is already taken.')
		else:
			return username		
		
	def clean(self):
		cleaned_data = super().clean()
		p1 = cleaned_data.get('password1')
		p2 = cleaned_data.get('password2')
		if p1 and p2:
			if p1 != p2:
				raise ValidationError('Passwords do not match')


class UserEditForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-sm','readonly':'readonly'}))
	first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	class Meta:
		model = User
		fields = {
			'username', 'first_name', 'last_name',
		}


class TeacherCreationForm(forms.Form):
	about = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'About'}))
	qualifications = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Qualifications'}))
	class Meta:
		model = User


class StudentCreationForm(forms.Form):
	class Meta:
		model = User


class UserCommentForm(forms.ModelForm):
	content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control border border-info', 'rows':1,}))

	class Meta:
		model = Comment
		fields = {'content',}


class PlaylistForm(forms.ModelForm):
	title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Title'}))
	description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Description', 'rows':2}))
	class Meta:
		model = Playlist
		fields = {'title', 'description', 'image'}
	field_order = ['title', 'description', 'image']
	

class VideoCreationForm(forms.ModelForm):
	title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Title'}))
	description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Description', 'rows':2}))
	class Meta:
		model = Video
		fields = {'title', 'description', 'file'}
	field_order = ['title', 'description', 'file']

repository/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Teacher, Student, Playlist, Video
from .forms import UserLoginForm, UserRegistrationForm, PlaylistForm, VideoCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from datetime import datetime
from django.http import HttpResponseRedirect, JsonResponse, Http404



# FOR TEACHERS REGISTRATION
def registration(request):
	if request.method == "POST":
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password1']
			user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
			user.save()
			if request.POST.get('exampleRadios') == 'teacher':
				Teacher.objects.create(user = user,)
			else:
				Student.objects.create(user = user,)
			login(request, user)
			return redirect('repository:home')
	else:
		form=UserRegistrationForm()
	return render(request, 'accounts/registration.html', {'form':form})


# FOR LOGIN
def userLogin(request):
	if request.method == 'POST':
		form =UserLoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				if request.POST.get('rememberMeCheck', None) == None:
					request.session.set_expiry(0)
				return redirect('repository:home')
			else:
				message = "Either user does not exists or password not correct. Please try again."
				context = {'form': form, 'message':message}
				return render(request, 'accounts/login.html', context)
	else:
		form = UserLoginForm()
		context = {'form': form}
		return render(request, 'accounts/login.html', context)

# FOR LOGOUT
def userLogout(request):
	logout(request)
	request.session.clear_expired()
	return redirect('repository:login')



def home(request):
	teacher = Teacher.objects.filter(user=request.user)
	#playlists = Playlist.objects.all()
	form = PlaylistForm()
	if request.user == teacher[0].user:
		playlists = Playlist.objects.filter(creator=request.user)

	context = {'playlists':playlists, 'form':form}
	return render(request, 'home.html', context)


def createPlaylist(request):
	if request.method == 'POST':
		form = PlaylistForm(data = request.POST, files=request.FILES)
		if form.is_valid():
			playlist = form.save(commit=False)
			playlist.creator = request.user
			playlist.created=datetime.now()
			playlist.save()
	return redirect('repository:home')


def ViewVideoPlaylist(request, id):
	form = VideoCreationForm()
	playlist = get_object_or_404(Playlist, id=id)
	videos = Video.objects.filter(playlist__id = playlist.id)
	context={'playlist':playlist, 'videos':videos, 'form':form}
	return render(request, 'playlist.html', context)


def CreateVideoPlaylist(request, id):
	playlist = get_object_or_404(Playlist, id=id)
	if request.method == 'POST':
		form = VideoCreationForm(data = request.POST, files=request.FILES)
		if form.is_valid():
			video = form.save(commit=False)
			video.playlist = playlist
			video.creator = request.user
			video.created=datetime.now()
			video.save()
	return HttpResponseRedirect(playlist.get_absolute_url())

repository/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

repository/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
<head>
	<title>Home</title>
</head>
<body>
	{% block content %}
	<div class="container-fluid">
		<div class="container my-3">
			<h3>Want to create playlist?</h3>
			<p>
			  <button class="btn btn-success" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
			    Create playlist
			  </button>
			</p>
			<div class="collapse" id="collapseExample">
			  <div class="card card-body">
			    <div class="col-md-6 offset-md-3">
				<form action="{% url 'repository:createPlaylist' %}" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{form.as_p}}
					<div class="container" style="text-align: center;">
						<button class="btn btn-primary" type="submit">Create Playlist</button>
					</div>
				</form>	
			</div>
			  </div>
			</div>
		</div><hr>
		<div class="container">
			<div class="row">
				<div class="col col-sm-3 col-md-4">
					{% for playlist in playlists %}
					<div class="card" style="width: 18rem;">
					  <img src="{{playlist.image.url}}" class="card-img-top .img-fluid" alt="Playlist Image" style="max-height:300px ">
					  <div class="card-body">
					    <h5 class="card-title">{{playlist.title}}</h5>
					    <p class="card-text">{{playlist.description}}</p>
					    <a href="{% url 'repository:ViewVideoPlaylist' id=playlist.id %}" class="btn btn-primary">Go to playlist</a>
					  </div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	{% endblock %}
</body>
</html>

repository/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

repository/templates/playlist.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
<head>
	<title>Home</title>
</head>
<body>
	{% block content %}
	<div class="container-fluid">
		<div class="container my-3">
			<h3>Want to add videos?</h3>
			<p>
			  <button class="btn btn-success" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
			    Add videos
			  </button>
			</p>
			<div class="collapse" id="collapseExample">
			  <div class="card card-body">
			    <div class="col-md-6 offset-md-3">
				<form action="{% url 'repository:CreateVideoPlaylist' id=playlist.id %}" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{form.as_p}}
					<div class="container" style="text-align: center;">
						<button class="btn btn-primary" type="submit">Add video</button>
					</div>
				</form>	
			</div>
			  </div>
			</div>
		</div><hr>
		<div class="container">
			<div class="row">
				
			</div>
		</div>
	</div>
	{% endblock %}
</body>
</html>