myvideo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repository.urls', namespace='repository')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

repository/urls.py
from django.urls import path
from .import views

app_name = 'repository'
urlpatterns = [
    path('login/', views.userLogin, name='userLogin'),
    path('registration/', views.registration, name='registration'),
    path('home/', views.home, name='home'),
    path('create/playlist', views.createPlaylist, name='createPlaylist'),
    path('playlist/video/<str:id>', views.ViewVideoPlaylist, name='ViewVideoPlaylist'),
    path('create/video/<str:id>', views.CreateVideoPlaylist, name='CreateVideoPlaylist'),
    #path('teacher/registration', views.teacherRegistration, name='teacherRegistration'),
]

repository/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Teacher(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	avatar= models.ImageField(blank=True)
	about = models.CharField(max_length=200, blank=True, null=True)
	qualification = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.user.username


class Playlist(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='playlist/images' , null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.creator.username

	def get_absolute_url(self):
		return reverse('repository:ViewVideoPlaylist', args=[self.id,])


class Video(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
	file = models.FileField(upload_to='videos/')
	description = models.CharField(max_length=200, blank=True)
	likes = models.ManyToManyField(User, related_name='likes', blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.creator.username


class Student(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	avatar = models.ImageField(blank=True)
	follow = models.ManyToManyField(Teacher, related_name='following', blank=True) 

	def __str__(self):
		return self.user.username


'''class Avatar(models.Model):
	avatar_user = models.ForeignKey(User, on_delete = models.CASCADE)
	file = models.ImageField(upload_to='profile_pics', null=True, blank=True)

	class Meta:
		verbose_name = 'avatarPhoto'
		verbose_name_plural = 'avatarPhotos'

	def __str__(self):
		return self.avatar_user.username'''


class Comment(models.Model):
	video = models.ForeignKey(Video, on_delete = models.CASCADE )
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='replies')
	content = models.TextField(max_length=200)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.content[:20], str(self.user.username))

repository/forms.py
from django import forms
from .models import Teacher, Playlist, Video, Student, Comment
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
	username= forms.CharField(label="Username",max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(UserCreationForm):
	first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control', 'placeholder':'Fist Name'}))
	last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Last Name'}))
	username = forms.CharField(label="Username",max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'}))
	password1 = forms.CharField(label="Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))
	password2 = forms.CharField(label="Confirm Password", max_length=100, min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Confirm Password'}))

	def clean_username(self):
		username = self.cleaned_data['username']
		qs = User.objects.filter(username=username)
		if qs.exists():
			raise ValidationError('Username is already taken.')
		else:
			return username		
		
	def clean(self):
		cleaned_data = super().clean()
		p1 = cleaned_data.get('password1')
		p2 = cleaned_data.get('password2')
		if p1 and p2:
			if p1 != p2:
				raise ValidationError('Passwords do not match')


class UserEditForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-sm','readonly':'readonly'}))
	first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}))
	class Meta:
		model = User
		fields = {
			'username', 'first_name', 'last_name',
		}


class TeacherCreationForm(forms.Form):
	about = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'About'}))
	qualifications = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Qualifications'}))
	class Meta:
		model = User


class StudentCreationForm(forms.Form):
	class Meta:
		model = User


class UserCommentForm(forms.ModelForm):
	content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control border border-info', 'rows':1,}))

	class Meta:
		model = Comment
		fields = {'content',}


class PlaylistForm(forms.ModelForm):
	title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Title'}))
	description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Description', 'rows':2}))
	class Meta:
		model = Playlist
		fields = {'title', 'description', 'image'}
	field_order = ['title', 'description', 'image']
	

class VideoCreationForm(forms.ModelForm):
	title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control form-control','placeholder':'Title'}))
	description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Description', 'rows':2}))
	class Meta:
		model = Video
		fields = {'title', 'description', 'file'}
	field_order = ['title', 'description', 'file']

repository/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Teacher, Student, Playlist, Video
from .forms import UserLoginForm, UserRegistrationForm, PlaylistForm, VideoCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from datetime import datetime
from django.http import HttpResponseRedirect, JsonResponse, Http404



# FOR TEACHERS REGISTRATION
def registration(request):
	if request.method == "POST":
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password1']
			user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
			user.save()
			if request.POST.get('exampleRadios') == 'teacher':
				Teacher.objects.create(user = user,)
			else:
				Student.objects.create(user = user,)
			login(request, user)
			return redirect('repository:home')
	else:
		form=UserRegistrationForm()
	return render(request, 'accounts/registration.html', {'form':form})


# FOR LOGIN
def userLogin(request):
	if request.method == 'POST':
		form =UserLoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				if request.POST.get('rememberMeCheck', None) == None:
					request.session.set_expiry(0)
				return redirect('repository:home')
			else:
				message = "Either user does not exists or password not correct. Please try again."
				context = {'form': form, 'message':message}
				return render(request, 'accounts/login.html', context)
	else:
		form = UserLoginForm()
		context = {'form': form}
		return render(request, 'accounts/login.html', context)

# FOR LOGOUT
def userLogout(request):
	logout(request)
	request.session.clear_expired()
	return redirect('repository:login')



def home(request):
	teacher = Teacher.objects.filter(user=request.user)
	#playlists = Playlist.objects.all()
	form = PlaylistForm()
	if request.user == teacher[0].user:
		playlists = Playlist.objects.filter(creator=request.user)

	context = {'playlists':playlists, 'form':form}
	return render(request, 'home.html', context)


def createPlaylist(request):
	if request.method == 'POST':
		form = PlaylistForm(data = request.POST, files=request.FILES)
		if form.is_valid():
			playlist = form.save(commit=False)
			playlist.creator = request.user
			playlist.created=datetime.now()
			playlist.save()
	return redirect('repository:home')


def ViewVideoPlaylist(request, id):
	form = VideoCreationForm()
	playlist = get_object_or_404(Playlist, id=id)
	videos = Video.objects.filter(playlist__id = playlist.id)
	context={'playlist':playlist, 'videos':videos, 'form':form}
	return render(request, 'playlist.html', context)


def CreateVideoPlaylist(request, id):
	playlist = get_object_or_404(Playlist, id=id)
	if request.method == 'POST':
		form = VideoCreationForm(data = request.POST, files=request.FILES)
		if form.is_valid():
			video = form.save(commit=False)
			video.playlist = playlist
			video.creator = request.user
			video.created=datetime.now()
			video.save()
	return HttpResponseRedirect(playlist.get_absolute_url())

repository/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<body>
  {% block content %}  
	
	<div class="container my-5">
		<div class="row">
			<div class="col-md-4 offset-md-4">
				<div class="container">
				<h1 class="" style="text-align: center;"><b>Please sign in</b></h1><br><br>
				{% if message %}
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
				     {{message}}
				</div>
				{% endif %}
				<form method="post">
					{% csrf_token %}
					{% for field in form %}
					<div class="fieldWrapper">
				        <div class="form-group">
					        <h5 style="text-align: center;">{{ field.label_tag }}</h5>
					        {{ field }}
					        {{ field.errors }}
				    	</div>
			    	</div>
					{% endfor %}

					<div class="form-group" style="text-align: center;">
			            <div class="form-check">
			                <input type="checkbox" name="rememberMeCheck" class="form-check-input" id="dropdownCheck">
			                <label class="form-check-label" for="dropdownCheck">
			                  Remember me
			                </label>
			            </div>
			        </div>

					<div class="container" style="text-align: center;">
					<button class="btn btn-primary" type="submit">Sign in</button>
					</div><br>
				</form>
				<div class="container" style="text-align: center;">
					<small><a class="" href="">Forgot Password?</a></small><br>
					<a class="" href="{% url 'repository:registration' %}">Don't have an account</a>
				</div>
				</div>
			</div>
		</div>
	</div>
	
	{% endblock %}
</body>
</html>

repository/templates/accounts/registration.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<body>
{% block content %}
<div class="container my-2">
	<div class="row">
		<div class="col-md-4 offset-md-4">
			<h1><strong>Create an account</strong></h1>
			<h4>It's quick and easy</h4><br>
			{% if messages %}
				{% for message in messages %}
					<a {% if message.tags %} 
						class="alert alert-danger" role="alert"
						{% endif %}>
					{{message}}
					</a>
				{% endfor %}
			{% endif %}
		
		<form action="" method="post">
		{% csrf_token %}
			<div class="row">
			    <div class="col">
			      {{ form.first_name }}
			    </div>
			    <div class="col">
			      {{ form.last_name }}
			    </div>
			</div><br>
			
			<div class="form-group-sm">
			<tr>
				<td>{{ form.username }}</td>
				<small  class="p-0" style="color:grey">
					<ul>
						<li>Your username should not be more than 15 characters. This value may contain only letters, numbers and @/./+/-/_ characters.</li>
					</ul>
				</small>
				<div class="alert p-0" style="color:red;">
				<td>{{ form.username.errors }}</td>
				</div>
			</tr>
			<tr>
				<td>{{ form.password1 }}</td>
				<small style="color:grey">
					<ul>
						<li>Your password can't be too similar to your other personal information.</li>
						<li>Your password must contain at least 8 characters.</li>
						<li>Your password can't be a commonly used password.</li>
						<li>Your password can't be entirely numeric.</li>
					</ul>	
				</small>
			</tr>
			<tr>
				<td>{{ form.password2 }}</td>
				<div class="alert p-0" style="color:red;">
				<td>{{ form.password2.errors }}</td>
				</div>
			</tr>
			</div>

		<h4>Which type of account do you want to create?</h4>
		<div class="form-check">
		  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="student" checked>
		  <label class="form-check-label" for="exampleRadios1">
		    Student
		  </label>
		</div>
		<div class="form-check">
		  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="teacher">
		  <label class="form-check-label" for="exampleRadios2">
		    Teacher
		  </label>
		</div>

		<p class="tnc" style="color:grey;font-size:12px;">By clicking Sign Up, you agree to our Terms, Data Policy and Cookie Policy. You may receive SMS notifications from us and can opt out at any time.</p>
		<div class="container" style="text-align: center;"><button type="submit" class="btn btn-info">Sign Up</button>
		</form></div><br>
		<p>Already Registered ? <a href="{% url 'repository:userLogin' %}">Login Here</a></p>
		</div>
	</div>
</div>
{% endblock %}
</body>
</html>